plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.library)
    alias(libs.plugins.compose)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.dokka)
    alias(libs.plugins.maven.publish)
}

kotlin {
    explicitApi()

    jvm()
    androidTarget()
    iosArm64()
    iosSimulatorArm64()
    iosX64()
    wasmJs { nodejs() }

    sourceSets {
        commonMain {
            dependencies {
                api(project(":core"))
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.components.resources)
            }
        }
        commonTest {
            dependencies {
                implementation(libs.kotlin.test)
            }
        }
        jvmTest {
            dependencies {
                implementation(compose.desktop.currentOs)
            }
        }
    }
}

android {
    namespace = "com.chrisjenx.kinvoicing.compose"
    compileSdk = 36
    defaultConfig {
        minSdk = 23
    }
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()
}

// --- wasmJs Node-compat for :render-compose --------------------------------
//
// Karma is deprecated upstream; KGP tracks its replacement in KT-66897 /
// KT-86175 (likely Kotlin 2.4). Until then, running Compose Multiplatform's
// wasmJs tests under `nodejs()` (instead of `browser()`) requires three
// pieces of glue, all wired below:
//
//   1. Patch `skiko.mjs` in-place. The Skia Emscripten loader has all three
//      of its Node-loader code paths dead-code-eliminated to `if (false) {`
//      gates (fs.readFileSync, crypto, buffer reads). Flipping them to
//      `if (ENVIRONMENT_IS_NODE) {` re-enables disk loading so Skiko can
//      bootstrap without a browser fetch.
//
//   2. Write a small ESM shim to `build/wasm/packages/<pkg>/node-test-shim.mjs`
//      that installs stub `window`/`document`/`navigator` globals (required
//      by js-reexport-symbols.mjs at module-evaluation time, otherwise
//      `window['<sym>'] = ...` ReferenceErrors immediately) and `awaits`
//      `skiko.awaitSkiko` so lazy bindings like `malloc` are resolved
//      before any image-decoding test calls into Skia.
//
//   3. Inject `--import file://<shim>` into `KotlinJsTest.nodeJsArgs`. Using
//      `--import` (instead of rewriting `static/runUnitTests.mjs`, which
//      KGP's task action regenerates between any doFirst hook and the
//      actual `node` exec) ensures the shim runs first, sets globals, and
//      awaits Skiko before the test entry evaluates. Top-level `await` in
//      ESM is supported by the Node version KGP bundles (v25).
//
// Skiko-version note: the `if (false)` substitution and the `awaitSkiko`
// promise export are properties of the current Skiko build. A Compose
// Multiplatform / Skiko version bump may change these and require updates.
val wasmJsTestPkgDir = rootProject.layout.buildDirectory
    .dir("wasm/packages/${rootProject.name}-${project.name}-test")
    .get().asFile
val skikoMjsFile = wasmJsTestPkgDir.resolve("kotlin/skiko.mjs")
val nodeTestShimFile = wasmJsTestPkgDir.resolve("node-test-shim.mjs")

val nodeTestShimContent = """
    // Generated by :render-compose. Pre-loaded via Node `--import` before
    // KGP's static/runUnitTests.mjs evaluates. See render-compose/build.gradle.kts.
    const windowStub = {
      addEventListener: () => {}, removeEventListener: () => {},
      postMessage: () => {},
      setTimeout: (fn, ms) => setTimeout(fn, ms),
      clearTimeout: (id) => clearTimeout(id),
      setInterval: (fn, ms) => setInterval(fn, ms),
      clearInterval: (id) => clearInterval(id),
      requestAnimationFrame: (fn) => setTimeout(() => fn(Date.now()), 16),
      cancelAnimationFrame: (id) => clearTimeout(id),
      location: { href: 'http://localhost/', origin: 'http://localhost' },
    };
    globalThis.window = windowStub;
    globalThis.self = windowStub;
    globalThis.document = {
      createElement: () => ({ getContext: () => null, style: {}, addEventListener: () => {} }),
      documentElement: { style: {} },
      body: { appendChild: () => {}, style: {} },
      addEventListener: () => {}, removeEventListener: () => {},
    };
    if (!globalThis.navigator) {
      globalThis.navigator = { userAgent: 'node', language: 'en-US', languages: ['en-US'] };
    }
    const skiko = await import('./kotlin/skiko.mjs');
    await skiko.awaitSkiko;
""".trimIndent()

tasks.matching { it.name == "wasmJsNodeTest" }.configureEach {
    // Opt this task out of Gradle's configuration cache: the doFirst closure
    // captures script-scope File and String values, which CC cannot
    // serialize. The captured values are trivial (paths + constant String),
    // and the rest of the build continues to benefit from CC.
    notCompatibleWithConfigurationCache(
        "Captures skiko.mjs / shim file paths and shim content for the Node-compat patch"
    )
    doFirst {
        if (skikoMjsFile.exists()) {
            val text = skikoMjsFile.readText()
            if (text.contains("if (false) {")) {
                skikoMjsFile.writeText(
                    text.replace("if (false) {", "if (ENVIRONMENT_IS_NODE) {")
                )
            }
        }
        nodeTestShimFile.parentFile.mkdirs()
        nodeTestShimFile.writeText(nodeTestShimContent + "\n")
    }
    (this as? org.jetbrains.kotlin.gradle.targets.js.testing.KotlinJsTest)?.let { jsTest ->
        val shimUrl = "file://${nodeTestShimFile.absolutePath}"
        if (!jsTest.nodeJsArgs.contains(shimUrl)) {
            jsTest.nodeJsArgs.add("--import")
            jsTest.nodeJsArgs.add(shimUrl)
        }
    }
}
