/*
 * wasmjs-node-compose
 * --------------------
 *
 * Makes Compose Multiplatform's wasmJs tests runnable under Node.js
 * (`nodejs()`) instead of the deprecated Karma+Chrome path (`browser()`).
 *
 * Apply to any KMP module that:
 *   - declares `wasmJs { nodejs() }` (not `browser()`),
 *   - depends on Compose Multiplatform / Skiko transitively (i.e. the
 *     wasmJs test bundle pulls in `skiko.mjs` and friends),
 *   - is built with Kotlin 2.3.20 / Compose Multiplatform 1.10.x.
 *
 * Usage:
 *
 *   plugins {
 *       alias(libs.plugins.kotlin.multiplatform)
 *       alias(libs.plugins.compose)
 *       id("wasmjs-node-compose")
 *   }
 *
 *   kotlin {
 *       wasmJs { nodejs() }
 *       // ...
 *   }
 *
 * What it does, on every `wasmJsNodeTest` execution:
 *
 *   1. Patch the generated `skiko.mjs` so its three `if (false) { ... }`
 *      Node-loader gates become `if (ENVIRONMENT_IS_NODE) { ... }`. The
 *      DCE'd code is still in the bundle and re-enables disk loading
 *      via `fs.readFileSync` so Skiko can bootstrap without `fetch`.
 *
 *   2. Write a small ESM shim next to the test bundle at
 *      `build/wasm/packages/<pkg>/node-test-shim.mjs`. The shim:
 *        - installs minimal `window` / `document` / `navigator` stubs
 *          (required by `js-reexport-symbols.mjs`, which does
 *          `window['<sym>'] = wasmApi[...]` at module-evaluation time),
 *        - awaits `skiko.awaitSkiko` so lazy Skia bindings like `malloc`
 *          resolve before any image-decoding test calls into Skia.
 *
 *   3. Inject `--import file://<shim>` into `KotlinJsTest.nodeJsArgs`.
 *      Node loads the shim before user code and supports top-level
 *      `await` in ESM, so `static/runUnitTests.mjs` evaluates with the
 *      globals in place and Skiko already initialized. We can't rewrite
 *      `runUnitTests.mjs` directly — KGP's KotlinJsTest task action
 *      regenerates it after any `doFirst` hook, every run.
 *
 * Caveat: the `if (false)` substitution and the `awaitSkiko` promise
 * export are properties of the current Skiko build. A Compose / Skiko
 * version bump can invalidate either; revisit if `wasmJsNodeTest`
 * starts failing with `malloc is not a function` or wasm fetch errors.
 *
 * Limitation: the patched `skiko.mjs` (which contains `await import("module")`
 * in its re-enabled Node branch) is NOT compatible with simultaneous
 * `wasmJs { nodejs(); browser() }`. Webpack's browser bundling chokes on
 * the Node-only import. Use one runner at a time.
 */
// `KotlinJsTest` from KGP is reached reflectively below to avoid pinning
// a KGP version on buildSrc's classpath. The task's `getNodeJsArgs()`
// returns a `MutableList<String>` we can mutate in place.

private val nodeTestShimContent = """
    // Generated by wasmjs-node-compose. Pre-loaded via Node `--import`
    // before KGP's static/runUnitTests.mjs evaluates.
    const windowStub = {
      addEventListener: () => {}, removeEventListener: () => {},
      postMessage: () => {},
      setTimeout: (fn, ms) => setTimeout(fn, ms),
      clearTimeout: (id) => clearTimeout(id),
      setInterval: (fn, ms) => setInterval(fn, ms),
      clearInterval: (id) => clearInterval(id),
      requestAnimationFrame: (fn) => setTimeout(() => fn(Date.now()), 16),
      cancelAnimationFrame: (id) => clearTimeout(id),
      location: { href: 'http://localhost/', origin: 'http://localhost' },
    };
    globalThis.window = windowStub;
    globalThis.self = windowStub;
    globalThis.document = {
      createElement: () => ({ getContext: () => null, style: {}, addEventListener: () => {} }),
      documentElement: { style: {} },
      body: { appendChild: () => {}, style: {} },
      addEventListener: () => {}, removeEventListener: () => {},
    };
    if (!globalThis.navigator) {
      globalThis.navigator = { userAgent: 'node', language: 'en-US', languages: ['en-US'] };
    }
    const skiko = await import('./kotlin/skiko.mjs');
    await skiko.awaitSkiko;
""".trimIndent()

tasks.matching { it.name == "wasmJsNodeTest" }.configureEach {
    // Resolve paths inside `configureEach` so the `doFirst` lambda below
    // only captures plain `java.io.File` and `String` values — never an
    // implicit `this` to the script class, which Gradle's configuration
    // cache refuses to serialize.
    val pkgDir = rootProject.layout.buildDirectory
        .dir("wasm/packages/${rootProject.name}-${project.name}-test")
        .get().asFile
    val skikoMjs = pkgDir.resolve("kotlin/skiko.mjs")
    val nodeTestShim = pkgDir.resolve("node-test-shim.mjs")
    val shimText = nodeTestShimContent

    // Belt-and-suspenders for CC: even with the local-only captures above,
    // the reflection call in step 3 holds a Method handle which CC also
    // can't serialize. Opt this single task out; the rest of the build
    // still benefits from CC.
    notCompatibleWithConfigurationCache(
        "wasmjs-node-compose: doFirst writes shim files and mutates nodeJsArgs for Node-compat patching"
    )

    doFirst {
        // 1. Patch skiko.mjs's Node-loader gates.
        if (skikoMjs.exists()) {
            val text = skikoMjs.readText()
            if (text.contains("if (false) {")) {
                skikoMjs.writeText(
                    text.replace("if (false) {", "if (ENVIRONMENT_IS_NODE) {")
                )
            }
        }
        // 2. Write the Node `--import` shim.
        nodeTestShim.parentFile.mkdirs()
        nodeTestShim.writeText(shimText + "\n")
        // 3. Append `--import file://<shim>` to KotlinJsTest.nodeJsArgs.
        //    Reached reflectively so buildSrc doesn't need KGP on its
        //    classpath (which would either conflict with the root build
        //    when `implementation` or vanish at runtime when `compileOnly`).
        //    KGP reads nodeJsArgs when building the node command in its
        //    `@TaskAction`, which runs after `doFirst`.
        @Suppress("UNCHECKED_CAST")
        val nodeJsArgs = runCatching {
            javaClass.getMethod("getNodeJsArgs").invoke(this) as MutableList<String>
        }.getOrNull()
        if (nodeJsArgs != null) {
            val shimUrl = "file://${nodeTestShim.absolutePath}"
            if (!nodeJsArgs.contains(shimUrl)) {
                nodeJsArgs.add("--import")
                nodeJsArgs.add(shimUrl)
            }
        }
    }
}
